language: r
sudo: false
cache: packages

env:
    global:
        - secure: "USeSuTh5+iLdRISnFYE0ZTvaEbkN4Yr/RNIy4jhNEbIrahssoviuGwa2fqVipH7iYbfgBW66yYG7+EzIihufR9IzhhhL1ieqj3crMQI6QHyCR4Q1D78aDQXbsow7xntMscxH/BVLQT1yLEdsFLfYlsNeltGjZ63+gvNp+C+/4GBsiqTVj/DdGX5hP3EEU5A1wo10fPCiqIRB4zIlJKUPjklm4AmJK9KOL2YCeW0mhpXcgSj2T05hLlBX1ZkdUu2l45jyYjsGAOeB2KlVZ8dWFND79BSEF3N/yZlqGsDUdifXAQf3mgIqKnFtZrC1aZunWP322WobKFUFaFBSXTW0FWCzMmsec/DWyNg9tFzvcNLusOlPSONc9+Noe+fCWchSWmRe+6nvyqAVxXSyQxoKqNPMM2TMAsCWctsfvunQrzSYtjor8mcJrnB4r1Ym7Px+e/QgMLu09GpkZfvbsnqaqn5OXgxO0LmLpiE+Fh1m+ARNZyy7ZBz8ahvyMMTMQfGLziWqDj72FdPC/GJOgdbeISJQeccDeHnl2keJkrfUV9ZwztzfqCv5LnREy7pGGQqQuVjRQjlk9PEJFczfrPiEHK2TUPxwR3RHUSkfoWICJ7RA6uc4HlTvP/hHczoCNLSc6dBiQzTNIslV5jzWReJ6eC7NAA+NWHRylJ1LxRsjaCo="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
