baseurl = "/"
title = "Monitor da Improbidade"
theme = "hugo-tracks-theme"
disqusShortname = "jurimetria"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$"]

[params]
  description = ""
  copyright = "&copy;2017 ABJ"
  sidebarAbout = [
    "O Instituto Não Aceito Corrupção é uma associação apartidária, sem fins lucrativos, fundada em julho de 2015. A entidade surgiu da articulação de um grupo de cidadãos que viu na crise política instalada a partir de junho de 2013, com os protestos de rua, uma oportunidade para transformar indignação em esforços estruturados para o enfrentamento da corrupção."
]

  # Contact page
  email = "relacionamento@abj.org.br"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "Historias"
  url = "historias/"

  [[params.navlinks]]
  name = "About"
  url = "sobre/"

  [[params.navlinks]]
  name = "Metodologia"
  url = "metodologia/"
  
  [[params.navlinks]]
  name = "Dashboard"
  url = "dashboard/"
  
  [[params.navlinks]]
  name = "Get in touch"
  url = "contato/"
  
  [params.social]
  facebook      = "https://www.facebook.com/institutonaoaceitocorrupcao/"
  email         = "contato@naoaceitocorrupcao.org.br"
  twitter       = "https://twitter.com/InstitutoInac"
  linkedin      = "https://www.linkedin.com/company-beta/10328094?pathWildcard=10328094"
  instagram     = "https://www.instagram.com/naoaceitocorrupcao/"
  github        = "https://github.com/abjur/cnc"
