baseurl = ""
title = "Monitor da Improbidade"
theme = "hugo-tracks-theme"
disqusShortname = "jurimetria"
googleAnalytics = ""

[params]
  description = "Describe your website"
  copyright = "&copy;2017 ABJ"
  sidebarAbout = [
    "INAC",
    "INAC2."
  ]

  # Contact page
  email = "contato@abj.org.br"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "inacSite"

  [[params.navlinks]]
  name = "Historias"
  url = "inacSite/historias/"

  [[params.navlinks]]
  name = "About"
  url = "inacSite/sobre/"

  [[params.navlinks]]
  name = "Metodologia"
  url = "inacSite/metodologia/"
  
  [[params.navlinks]]
  name = "Get in touch"
  url = "inacSite/contato/"
  
  [params.social]
  facebook      = "full page or profile url in facebook"
  googleplus    = "full profile url in googleplus"
  email         = "email@example.com"
  twitter       = "full profile url in twitter"
  linkedin      = "full profile url in linkedin"
  stackoverflow = "full profile url in stackoverflow"
  instagram     = "full profile url in instagram"
  github        = "full profile url in github"
