---
title: "Rascunhos"
author: "J"
date: "March 13, 2017"
output: html_document
---

```{r eval=FALSE}
library(crosstalk)
library(leaflet)
library(DT)

# Wrap data frame in SharedData
sd <- SharedData$new(quakes[sample(nrow(quakes), 100),])

# Create a filter input
filter_slider("mag", 
              "Magnitude", 
              sd, 
              column=~mag, 
              step=0.1, 
              width=250)

# Use SharedData like a dataframe with Crosstalk-enabled widgets
bscols(
  leaflet(sd) %>% 
    addTiles() %>% 
    addMarkers(),
  datatable(sd, 
            extensions="Scroller", 
            style="bootstrap", 
            class="compact", 
            width="100%",
            options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))
)
```

```{r eval=FALSE}
library(ggplot2)
library(shiny)
library(leaflet)
data('br_uf_map', package = 'abjData')

sd <- SharedData$new(tidy_cnc, ~id_condenacao)

library(geojsonio)






dd <- g2@data
dd$pol <- g2@lines
dd$lat <- purrr::map_dbl(dd$pol, ~.x@Lines[[1]]@coords[,2][1])
dd$lon <- purrr::map_dbl(dd$pol, ~.x@Lines[[1]]@coords[,1][1])
sd <- SharedData$new(dd, ~id)
bscols(
  filter_select('aff', 
                label = 'Selecione o estado', 
                sharedData = sd, 
                group = ~name,
                multiple = FALSE
  ), 
  {
    l <- leaflet(sd) %>% 
      addTiles() %>% 
      addMarkers()
    for (i in 1:nrow(sd$data())) {
      l <- addPolylines(l, data = sd$data()$pol[[i]])
    }
    l
  }
  
)


sd <- SharedData$new(br_uf_map, ~id)
bscols(
  filter_select('aff', 
                label = 'Selecione o estado', 
                sharedData = sd, 
                group = ~id,
                multiple = FALSE
  ), sd$data() %>% 
      leaflet() %>% 
      addTiles() %>% 
      addPolygons(lng = ~long, 
                  lat = ~lat)
)



filter_slider("sep", 
              "Sepal", 
              sd2, 
              column=~Sepal.Length, 
              step=0.1, 
              width=250)

# renderPlot({
  df <- sd2$data(withSelection = TRUE, withFilter = TRUE)
  ggplot(df, aes(Sepal.Length, Sepal.Width,
    color = selection_factor(df))) +
    geom_point() +
    scale_color_selection("#444444", "skyblue1")
# })
```



```{r}
tab_count %>% 
  group_by(assunto_nm_all) %>% 
  mutate(teve_all = teve_all %>% 
           str_replace_all(',', '\n') %>% 
           fct_reorder(n)) %>% 
  ggplot(aes(x = teve_all, y = n)) +
  geom_col(position = 'dodge') +
  facet_wrap(~assunto_nm_all, scales = 'free', ncol = 3) +
  theme_bw()
```

<!-- PESSOAS ----------------------------------------------------------------->

Relatórios

- Pessoas
- Processos
- Condenações

# Pessoas

```{r eval=FALSE}
tidy_pessoa <- tidy_vis %>% 
  # filtro do parametro
  filter(esfera_processo == esfera_processo) %>% 
  # filtro do parametro
  select(id_pessoa, tipo_pessoa:cod, everything()) %>% 
  group_by(id_pessoa, tipo_pessoa, nm_pessoa, sexo, publico, esfera,
           orgao, cargo, uf, cod) %>% 
  tidyr::nest()
```


O que quero saber das pessoas?

- perfil: sexo, publico, 

```{r}
# tab <- tidy_cnc %>% 
#   mutate(tempo_processo = runif(n())) %>% 
#   create_vis(cruzamentos)
```

<!-- ---------------------------------------------------------------------- -->

Análises

- condenações com teve_*

Mapas

- volume de pessoas por unidade federativa (/ populacao)
- aff

<!-- ----------------------------------------------------------------------- -->

## Caracterização

- coluna com mapas

## Punições

- mapa assuntos x punicoes

## Danos

## Tempos


## Componentes

## Evolução



  

























